export const C = Object.freeze({
  TICK: 1 / 60, SNAPSHOT_EVERY: 3, INPUT_HZ: 30, INTERPOLATION_MS: 100,
  MAX_RAIDERS: 8, MAX_ROOMS: 8, MAX_ACTIVE_CHUNKS: 144, MAX_RAGDOLLS: 8,
  BUILDING_STRENGTH: 1.7, WALK_CHIP: 3, WALK_CHIP_INTERVAL: .7, HAND_CONTACT_INTERVAL: .36,
  GIANT_SCALE: 14, GIANT_SPEED: 13, TURN_SPEED: Math.PI / 2, GIANT_BODY_RADIUS: 4.2, GIANT_BOUND: 125,
  SOAR_SPEED: 32, SOAR_BOOST_SPEED: 42, DODGE_SPEED: 48, DODGE_SECONDS: .19, DODGE_COOLDOWN: 1.2, DODGE_FUEL: .12,
  SOAR_BREACH_LIMIT: 6, SOAR_DEBRIS_GRACE: .9,
  MISSILE_SPEED: 55, MISSILE_LIFETIME: 3.6, MISSILE_COOLDOWN: .8, MAX_MISSILES: 8, MISSILE_RADIUS: 6, MISSILE_ENERGY: 300, MISSILE_HOMING_RANGE: 75, MISSILE_HOMING_CONE: .38, MISSILE_TURN_RATE: .48,
  CAR_HP:70, CAR_DAMAGE_SPEED:4, CAR_HIT_INTERVAL:.25,
  HAND_RADIUS: 1.55, HEAD_RADIUS: 2.05, MAX_HAND_SPEED: 85,
  PLAYER_SPEED: 11, BOOST_SPEED: 20, ASCEND_SPEED: 11, ASCEND_BURN: .095, PLAYER_HP: 100,
  BOSS_HP: 2600, // Maximum colossus HP per raider; solo/empty-room baseline.
  MATCH_SECONDS: 240, RESPAWN_SECONDS: 5,
  ARENA_HALF: 166, KILL_HALF: 205, MAX_ALTITUDE: 150, FIRE_INTERVAL: .18, SHOT_DAMAGE: 10,
  SHOT_RANGE: 160, GRAVITY: -9.81, CHUNK_LIFETIME: 35, INVULNERABLE_SECONDS: 2.5,
  // Raider breach shot: a charged bolt that cracks structure and staggers the giant.
  HEAVY_DAMAGE: 42, HEAVY_STRUCTURE: 70, HEAVY_COOLDOWN: 3, HEAVY_FUEL: .22, HEAVY_RANGE: 190, HEAVY_CHARGE_SECONDS: .7,
  // Overloaded bays fail after a short creak so cascades read as progressive collapse.
  COLLAPSE_DELAY: .65, COLLAPSE_JITTER: .35, CRUMBLE_SPEED: 11, SPLIT_SPEED: 7,
  COLLISION: {WORLD: 1, DEBRIS: 2, PLAYER: 4, GIANT: 8, RAGDOLL: 16}
});
export const group = (membership, filter = 65535) => ((membership << 16) | filter) >>> 0;
export const TEAM_COLORS = [0x67e8f9, 0xffbb69, 0xa9ff98, 0xc4a0ff, 0xff89ac, 0xffff9c, 0x84afff, 0xffffff];
// Player snapshot flag bits.
export const F = Object.freeze({DEAD:1, RAG:2, SHIELD:4, BOT:8, SOAR:16, DODGE:32, CHARGING:64});
