// Bake the downloaded Quaternius Spacesuit into one posed, colored pilot mesh.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
globalThis.ProgressEvent??=class{constructor(type,values){Object.assign(this,values);}};
const {scene,animations}=await new GLTFLoader().parseAsync(await readFile('.cache/asset-downloads/Spacesuit.gltf','utf8'),'');
const mixer=new T.AnimationMixer(scene),clip=animations.find(a=>a.name==='Idle_Gun_Pointing');mixer.clipAction(clip).play();mixer.update(.3);scene.updateMatrixWorld(true);
const wrist=scene.getObjectByName('WristR');
// Exporter's source forward is +Z; our game and weapons look down -Z.
const turn=new T.Matrix4().makeRotationY(Math.PI),parts=[];
scene.traverse(node=>{if(!node.isMesh)return;node.skeleton?.update();const g=node.geometry.clone(),p=g.attributes.position,tmp=new T.Vector3();for(let i=0;i<p.count;i++){tmp.fromBufferAttribute(p,i);if(node.isSkinnedMesh)node.applyBoneTransform(i,tmp);tmp.applyMatrix4(node.matrixWorld).applyMatrix4(turn);p.setXYZ(i,...tmp.toArray());}g.computeVertexNormals();const geo=g.index?g.toNonIndexed():g,mats=Array.isArray(node.material)?node.material:[node.material],colors=new Float32Array(geo.attributes.position.count*3);for(const group of geo.groups.length?geo.groups:[{start:0,count:geo.attributes.position.count,materialIndex:0}]){const color=mats[group.materialIndex].color;for(let i=group.start;i<group.start+group.count;i++)color.toArray(colors,i*3);}geo.setAttribute('color',new T.BufferAttribute(colors,3));for(const name of Object.keys(geo.attributes))if(!['position','normal','color'].includes(name))geo.deleteAttribute(name);geo.clearGroups();parts.push(geo);});
const geo=mergeGeometries(parts);geo.computeBoundingBox();const size=geo.boundingBox.getSize(new T.Vector3()),center=geo.boundingBox.getCenter(new T.Vector3()),scale=2.2/size.y;const weaponMount=wrist.getWorldPosition(new T.Vector3()).applyMatrix4(turn).sub(new T.Vector3(center.x,geo.boundingBox.min.y,center.z)).multiplyScalar(scale).toArray();geo.translate(-center.x,-geo.boundingBox.min.y,-center.z);geo.scale(scale,scale,scale);
const doc={asset:{version:'2.0',generator:'Colossus City: Quaternius Spacesuit, posed and baked, -Z forward'},scene:0,scenes:[{nodes:[0]}],nodes:[{name:'Raider_ArmoredPilot',mesh:0,extras:{weaponMount}}],meshes:[{primitives:[{attributes:{},material:0}]}],materials:[{name:'Industrial flight armor',pbrMetallicRoughness:{metallicFactor:.45,roughnessFactor:.55}}],buffers:[{byteLength:0}],bufferViews:[],accessors:[]},chunks=[];let bytes=0;
for(const [name,semantic]of [['position','POSITION'],['normal','NORMAL'],['color','COLOR_0']]){const a=geo.attributes[name],array=new Float32Array(a.array);doc.bufferViews.push({buffer:0,byteOffset:bytes,byteLength:array.byteLength,target:34962});const accessor={bufferView:doc.bufferViews.length-1,componentType:5126,count:a.count,type:'VEC3'};if(name==='position'){geo.computeBoundingBox();accessor.min=geo.boundingBox.min.toArray();accessor.max=geo.boundingBox.max.toArray();}doc.meshes[0].primitives[0].attributes[semantic]=doc.accessors.length;doc.accessors.push(accessor);chunks.push(Buffer.from(array.buffer));bytes+=array.byteLength;}
doc.buffers[0].byteLength=bytes;let json=Buffer.from(JSON.stringify(doc));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);const header=Buffer.alloc(20);header.writeUInt32LE(0x46546c67);header.writeUInt32LE(2,4);header.writeUInt32LE(28+json.length+bytes,8);header.writeUInt32LE(json.length,12);header.writeUInt32LE(0x4e4f534a,16);const bin=Buffer.alloc(8);bin.writeUInt32LE(bytes);bin.writeUInt32LE(0x004e4942,4);await mkdir('public/assets/imported/raider',{recursive:true});await writeFile('public/assets/imported/raider/armored-pilot.glb',Buffer.concat([header,json,bin,...chunks]));console.log({triangles:geo.attributes.position.count/3,size:geo.boundingBox.getSize(new T.Vector3()).toArray(),bytes:28+json.length+bytes});
